version: 0.2

env:
  variables:
    AWS_REGION: "ap-northeast-1"
    REACT_APP_API_SERVICE_URL: "http://hoge-655470985.ap-northeast-1.elb.amazonaws.com"

phases:
  pre_build:
    commands:
      - echo logging in to ecr...
      - >
        aws ecr get-login-password --region ${AWS_REGION} \
          | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
      - docker pull ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/backend:prod || true
      - docker pull ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/frontend:builder || true
      - docker pull ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/frontend:prod || true
  build:
    commands:
      - echo building images app-backend, app-frontend
      - >
        docker build \
          --cache-from ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/backend:prod \
          -f web-ocr/backend/Dockerfile.prod \
          -t ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/backend:prod \
          ./web-ocr/backend
      - >
        docker build \
          --target builder \
          --cache-from ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/frontend:builder \
          -f web-ocr/frontend/Dockerfile.prod \
          -t ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/frontend:builder \
          --build-arg NODE_ENV=production \
          --build-arg REACT_APP_API_SERVICE_URL=$REACT_APP_API_SERVICE_URL \
          ./web-ocr/frontend
      - >
        docker build \
          --cache-from ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/frontend:prod \
          -f web-ocr/frontend/Dockerfile.prod \
          -t ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/frontend:prod \
          ./web-ocr/frontend
  post_build:
    commands:
      - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/backend:prod
      - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/frontend:builder
      - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/frontend:prod